apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart 
          image: irhadudheen/cart_service:latest

---
apiVersion: v1
kind: Service
metadata:
  name: cart-srv
spec:
  type: NodePort
  selector:
    app: cart 
  ports:
    - name: cart-srv-port
      protocol: TCP
      port: 4042 
      targetPort: 4042 
      