apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product 
          image: irhadudheen/shopping:shopping

---
apiVersion: v1
kind: Service
metadata:
  name: product-srv
spec:
  type: NodePort
  selector:
    app: product 
  ports:
    - name: product-srv-port
      protocol: TCP
      port: 4041 
      targetPort: 4041 
      