apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user 
          image: irhadudheen/shopping:shopping

---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  type: NodePort
  selector:
    app: user 
  ports:
    - name: user-srv-port
      protocol: TCP
      port: 4040 
      targetPort: 4040 
      